# Generated by Django 4.2.7 on 2023-12-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('birthdate', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('accounts', models.JSONField()),
                ('tier_and_details', models.JSONField()),
            ],
        ),
    ]
